services:
  ros2_workspace:
    build:
      context: .
      dockerfile: Dockerfile
      # Build natively for host architecture (auto-detected)
    image: hawkeye-ros:latest
    container_name: hawkeye-ros
    stdin_open: true
    tty: true
    privileged: true  
    volumes:
      - /dev:/dev     
      - ./src:/ros2_ws/src
    working_dir: /ros2_ws
    command: bash -lc "colcon build --packages-skip imaging && source install/setup.bash && tail -f /dev/null"
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    ipc: host