services:
  ros2_workspace:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      # Build natively for host architecture (auto-detected)
    image: hawkeye-ros:latest
    container_name: hawkeye-ros
    stdin_open: true
    tty: true
    privileged: true  
    volumes:
      - /dev:/dev     
      - ./src:/ros2_ws/src
      - ./test_images:/ros2_ws/test_images
    working_dir: /ros2_ws
    command: bash -lc "colcon build --packages-skip imaging && source install/setup.bash && tail -f /dev/null"
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0

      # Orchestrator configuration
      # This is only for LOCAL DEVELOPMENT where the signaling server is running on the host machine - in prod this should be set to the actual remote signaling server URL
      - WEBRTC_SIGNALING_URL=ws://host.docker.internal:8081
      # Topics
      - OBJECT_DETECTION_TOPIC=object_detection/image
      - IMAGE_REQUEST_TOPIC=image_request
    ipc: host
volumes:
  ros2_ws_build:
  ros2_ws_install:
