services:
  ros2_workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: hawkeye-ros:latest
    container_name: hawkeye-ros
    stdin_open: true
    tty: true
    volumes:
      - ./src:/ros2_ws/src
      - ./test_images:/ros2_ws/test_images
      - ros2_ws_build:/ros2_ws/build
      - ros2_ws_install:/ros2_ws/install
    working_dir: /ros2_ws
    command: /bin/bash -c "colcon build && source install/setup.bash && /bin/bash"
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0

      # Orchestrator configuration
      - GCOM_WEBSOCKET_URL=ws://host.docker.internal:8765
      - WEBRTC_SIGNALING_URL=ws://host.docker.internal:8766
      # Topics
      - OBJECT_DETECTION_TOPIC=object_detection/image
      - IMAGE_REQUEST_TOPIC=image_request
    ipc: host
volumes:
    ros2_ws_build:
    ros2_ws_install:
